@startuml Diagrama_ER_APT
title Diagrama Entidad-Relación - Proyecto APT

entity Usuario {
    *id: uuid <<PK>>
    nombre: text
    email: text
    rol: rol_usuario
    activo: bool
    creado_en: timestamp
    created_at: timestamp
    updated_at: timestamp
}

entity Producto {
    *id: int <<PK>>
    codigo_barras: text
    marca: text
    modelo: text
    compatibilidad: text
    sku: text
    nombre: text
    categoria_id: int <<FK>>
}

entity Categoria {
    *id: int <<PK>>
    nombre: text
    parent_id: int <<FK>>
    activo: bool
}

entity Imagen {
    *id: int <<PK>>
    producto_id: int <<FK>>
    storage_path: text
    hash_archivo: text
    ancho: int
    alto: int
    tomado_en: timestamp
    tomado_por: uuid <<FK>>
    notas: text
}

entity Movimiento {
    *id: int <<PK>>
    fecha: timestamp
    tipo: tipo_mov
    producto_id: int <<FK>>
    cantidad: numeric
    usuario_id: uuid <<FK>>
    motivo: text
    referencia_ext: text
    created_at: timestamp
    updated_at: timestamp
}

entity Stock {
    *producto_id: int <<PK, FK>>
    cantidad: int
}

entity Inspeccion {
    *id: int <<PK>>
    imagen_id: int <<FK>>
    producto_id: int <<FK>>
    modelo_id: int <<FK>>
    etiqueta: text
    confianza: numeric
    detalles: jsonb
}

entity ModeloIA {
    *id: int <<PK>>
    nombre: text
    version: text
    proveedor: text
    uri: text
    created_at: timestamp
    updated_at: timestamp
}

' Relaciones
Usuario ||--o{ Movimiento : realiza
Producto ||--o{ Imagen : tiene
Producto ||--|| Stock : posee
Producto }o--|| Categoria : pertenece
Producto ||--o{ Movimiento : genera
Producto ||--o{ Inspeccion : verifica
Imagen ||--o{ Inspeccion : contiene
ModeloIA ||--o{ Inspeccion : utiliza

@enduml
